@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho



entity "users"  {
    * **email : string  <<PK>>**
    --
    *password : string
    *firstname: string
    *lastname: string
    *birthdate: string
    *phone: string
}


entity "clients"  {
  * **client_id : string <<PK>> **
  --
  *email : string <<FK>>
  *client_secret : string
  *client_name: string
  client_logo: string
  client_description: string
  *client_homepage: string
  *client_redirect_uris: string
}

<> manages
users }|-- manages
manages -o{ clients

' entity "authorization"  {
'   * **id : string <<PK>> **
'   --
'   *authorization_code : string <<FK>>
'   *client_id: string <<FK>>
'   *email: string <<FK>>
'   *expires_at: uint256
'   *timestamp: uint256
' }

' entity "token"  {
'   * ** id : string <<PK>> **
'   --
'   *access_token : string
'   *client_id : string <<FK>>
'   *email : string <<FK>>
'   *expires_at : uint256
'   *timestamp : uint256
' }



'"users" }|--o{ "clients"
'n"users" }|--o{ "authorization"
'"users" }|--o{ "token"
'n"clients" }|--o{ "authorization"
'"clients" }|--o{ "token"

@enduml