@startuml
Actor User
User -> LoginView : Click register
activate LoginView
LoginView -> RegisterPage : Open register form
deactivate LoginView
activate RegisterPage
RegisterPage --> User : diaplay
User -> RegisterPage : Enter username, firstname, lastname, e-mail,\n password and password confirmation
RegisterPage -> Database : check username
activate Database
alt if username is not exist
Database --> RegisterPage : username is non exist
else the username exist
Database --> RegisterPage : username is already used
RegisterPage --> User : send warning message
end
RegisterPage -> Database : check password
alt if password not against the requirement
Database --> RegisterPage : password is valid
else password against the requirement
Database --> RegisterPage : password not following the requirement
RegisterPage --> User : send warning message
end
RegisterPage -> Database : check password confirmation
alt if password is matched
Database --> RegisterPage : password is matched
else password is mismatched
Database --> RegisterPage : password is mismatched
RegisterPage --> User : send warning message
end
RegisterPage -> Database : create new user
deactivate RegisterPage
Database --> LoginView : redirect
deactivate Database
activate LoginView
LoginView --> User : display
deactivate LoginView
@enduml
