@startuml
actor User
User -> "Web Service" ++: Enter user detail\nemail and password
"Web Service" -> "Web Service" ++: Validate user details
alt Invalid user detail
    "Web Service" --> User --: Response "Invalid user details"
    
else Valid user details
    "Web Service" -> "Authorization Server" --++: Request Authentication 
    "Authorization Server" -> "Authorization Server" ++: Encrypted user details
    "Authorization Server" -> "Blockchain" --++: Call resource User for validate
    "Blockchain" --> "Authorization Server" --: Response type boolean
    note right
        Call function getUser() return true/false 
        *true is correct user`
    end note

    alt Incorrect user (false)
        "Authorization Server" --> "Web Service" ++: 
        "Web Service" --> User --: Response "User is incorrect"
    else Correct user (true)
        "Authorization Server" -> "Authorization Server" ++: Verified identity and generate Authorization code
        "Authorization Server" -> "Blockchain" --++: Send authorization code  
        "Blockchain" --> "Authorization Server" --: Response transaction detail
        "Authorization Server" --> "Web Service" --++: Response with data
    end
    
end
"Web Service" --> User --: Response 
@enduml