@startuml
actor User
User -> "Register Page" ++: Enter user details
"Register Page" -> "Register Page" ++: Validate user details
alt Invalid user detail
    "Register Page" --> "Register Page" --: Response "Invalid user details"
    
else Valid user details
    "Register Page" -> "IAM Service" ++: Validate user and redundancy of user 
    "IAM Service" -> "Blockchain" ++: Call resource user status is available 
    "Blockchain" --> "IAM Service" --: Response type boolean
    note right
        Call function isUser() return true/false 
        *true is redundancy
    end note
    alt Redundancy user (true)
        "IAM Service" --> "Register Page" : Response "User is already"
    else User Available (false)
        "IAM Service" -> "Blockchain" ++: Send encrypted user details
        "Blockchain" --> "IAM Service" --: Response transaction details
        "IAM Service" --> "Register Page" --:Response "Register Successfully"
    end
end
@enduml