@startuml EntityDiagramBlockchain
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho


entity "clients"  {
  * **client_id : string <<PK>> **
  --
  *client_secret : string
  *client_name: string
  client_logo: string
  client_description: string
  *client_homepage: string
  *client_redirect_uri: string
  *client_owner: address
  *is_active: boolean
  *update_date: int256
  *create_date: int256
}


entity "authorization"  {
  * **authorization_id : string <<PK>> **
  --
  *authorization_code : string
  *client_id: string <<FK>>
  scope: string
  *user: address
  *expires_at: uint256
  *is_active: boolean
  *create_date: uint256
}

entity "token"  {
  * ** token_id : string <<PK>> **
  --
  *authorization_id: string <<FK>>
  *access_token : string
  *access_token_expires_at : uint256
  *refesh_token : string
  *refesh_token_expires_at : uint256
  scope: string
  *client_id : string <<FK>>
  *user : address
  *is_active: boolean
  *create_date : uint256
}

"clients" }|--o{ "authorization"
"clients" }|--o{ "token"
"authorization" ||--|| "token"

@enduml