@startuml refreshToken
title **Refresh Token** Seqeunce Diagram
hide footbox
actor User
autonumber "<b>(0)"
"User" --> "Authentication Server" ++: Authorization request
"Authentication Server" --> "User" --: Invalid Token error
"User" --> "Authentication Server" ++: Refresh token
"Authentication Server" --> "Authentication Server" : Generate new access token and encrypt
"Authentication Server" --> "Crypto Wallet" --++: Generate transaction signature, access token
"Crypto Wallet" --> "User" --: Response transaction signature and wait for user confirmation
alt User denied transaction signature (false)
    autonumber stop
    "User" --> "Crypto Wallet" ++: User denied transaction signature
    "Crypto Wallet" --> "Authentication Server" --++: Denied access token grant, Transaction signature
    "Authentication Server" --> "User" --: Access token request denied
else ser confirmation transaction signature (true)
                    autonumber resume
                    "User" --> "Crypto Wallet" ++: User confirmed transaction signature
                    "Crypto Wallet" --> "Authentication Server" --++: Confirmed transaction signature , Access token
                    "Authentication Server" --> "Blockchain" --++: Send access token credentials encrypted
                    "Blockchain" --> "Authentication Server" --++: Successful transaction response
                    "Authentication Server" --> "User" --: Grant new access token,refresh token response

end
@enduml