@startuml revokeToken
title **Revoke Token** Seqeunce Diagram
hide footbox
actor User
autonumber "<b>(0)"
"User" --> "Authentication Server" ++: Authentication with token to be revoke
"Authentication Server" --> "Authentication Server" : Verify user can revoke token
"Authentication Server" --> "Crypto Wallet" --++: Generate transaction signature, revoke token
"Crypto Wallet" --> "User" --: Response transaction signature and wait for user confirmation
alt User denied transaction signature (false)
    autonumber stop
    "User" --> "Crypto Wallet" ++: User denied transaction signature
    "Crypto Wallet" --> "Authentication Server" --++: Denied revoke, Transaction signature
    "Authentication Server" --> "User" --: Revoke token request denied
else ser confirmation transaction signature (true)
                    autonumber resume
                    "User" --> "Crypto Wallet" ++: User confirmed transaction signature
                    "Crypto Wallet" --> "Authentication Server" --++: Confirmed transaction signature , revoke token
                    "Authentication Server" --> "Blockchain" --++: revoke access token
                    "Blockchain" --> "Authentication Server" --++: Successful transaction response
                    "Authentication Server" --> "User" --: Revoke token successful response

end
@enduml