@startuml
title **Logout** Seqeunce Diagram
hide footbox
Actor User
autonumber "<b>(0)"
User -> LogoutView : Click Logout
activate LogoutView
LogoutView -> LoginView:redirect()
deactivate LogoutView
activate LoginView
LoginView --> User : Display()
deactivate LoginView
@enduml
