@startuml Web Client Register with Credentials 
title **Web Client Register with Credentials ** Sequence Diagram
hide footbox
Actor User
autonumber "<b>(0)"
User-> RegisterPage ++: Click Register\nRedirect /auth?signup=true 
RegisterPage --> User --: Response Register form
User -> RegisterPage ++: Enter name, email, password \nSubmit Register form
RegisterPage -> RegisterPage ++--: Verify the user credentials format.
alt Invalid user credentials format
    RegisterPage --> "User" : Alert waning message in register form\n"Invalid user data format"
else Valid user credentials format
    RegisterPage -> "Web Client" --++: Check the email available in the system
    "Web Client" -> "Database" --++:  Request query email of \nuser entity in database 
    "Database" --> "Web Client" --++: Response existing or \nnon-existent email 
    alt Email is existing
    autonumber stop
        "Web Client" --> RegisterPage ++: Response warning message \n"Email already used."
        "RegisterPage" --> "User" --: Alert warning message in register form
    else Email is not exist
    autonumber resume
        "Web Client" -> "Database" --++: Insert new user into the database
        Database --> "Web Client" --++: Response userId
        "Web Client" --> "RegisterPage" --++:  Response success message\n"Register successful."
        "RegisterPage" --> "User" --: Alert success message in register form"\nRedirect to /auth
    end
end
@enduml
