@startuml
title **Search Task** Seqeunce Diagram
hide footbox
Actor User
autonumber "<b>(0)"
User -> TaskList : Enter search information
activate TaskList
TaskList -> TaskList: find tasks
activate TaskList
deactivate TaskList
TaskList --> User: display tasks
deactivate TaskList
@enduml
