@startuml
Actor User
User -> ShareList : click cross mark behind share
activate ShareList
ShareList -> DeleteView : request revoke share permission
activate DeleteView
DeleteView -> User : send confirmation message
User -> DeleteView : confirm
DeleteView -> Database : revoke share permission
activate Database
Database --> ShareList : redirect
deactivate Database
deactivate DeleteView
ShareList --> User : display
deactivate ShareList
@enduml
