@startuml
title **Share Task** Seqeunce Diagram
hide footbox
Actor User
autonumber "<b>(0)"
User -> ShareCreate : Enter target's username
activate ShareCreate
ShareCreate -> Database : check username
activate Database
alt if username exist
Database --> ShareCreate  : username is exist
else username not exist
Database --> ShareCreate  : username is non exist
ShareCreate  --> User : send warning message
end
ShareCreate -> Database : add new share permission
deactivate ShareCreate
Database --> User : Display()
deactivate Database
@enduml
