@startuml
title **Edit Task** Seqeunce Diagram
hide footbox
Actor User
autonumber "<b>(0)"
User -> TaskList : Click Task's title
activate TaskList
TaskList -> TaskUpdate : open TaskUpdate's view
activate TaskUpdate
TaskUpdate --> User : display
User -> TaskUpdate : edit Task's title, \ndescription and \ncomplete status
TaskUpdate -> Database : save the change
activate Database
Database --> TaskList : redirect
deactivate Database
deactivate TaskUpdate
TaskList --> User : display
deactivate TaskList
@enduml
