@startuml
title **Rename Task** Seqeunce Diagram
hide footbox
Actor User
autonumber "<b>(0)"
User -> TaskList : Click Task's title
activate TaskList
TaskList -> TaskUpdate : open TaskUpdate's view
activate TaskUpdate
User -> TaskUpdate : rename task
TaskUpdate -> Database : save the change
activate Database
Database --> TaskList : redirect
deactivate Database
deactivate TaskUpdate
TaskList --> User : display
deactivate TaskList
@enduml
