@startuml Web Client Update Status To-do List
title **Web Client Update Status To-do List** Seqeunce Diagram
hide footbox
Actor User
autonumber "<b>(0)"
User -> "To-do List Page" ++: Update Status To-do list selected
"To-do List Page" -> "Web Client" --++: Request update status to-do list \nPUT Parameter: listId , complete [true,false]
"Web Client" -> "Database" --++: Update status to-do list of listId selected into database
"Database" --> "Web Client" --++: Response listId and list info
"Web Client" --> "To-do List Page" --++: Update the to-do list on the page
"To-do List Page" --> "User" --: Response to-do list page
@enduml
