@startuml Web Server Create client
title **Web Server Create client** Seqeunce Diagram
hide footbox
actor User
autonumber "<b>(0)"
"User" --> "Web Server" ++: Client manage request\nGET /developer
"Web Server" --> "User" --: Connect wallet request
"User" --> "Crypto Wallet" ++: Client manage connect wallet request
"Crypto Wallet" --> "Web Server" --++: Wallet credential request
"Web Server" --> "Web Server" : Wallet verification and chain Id
autonumber stop
"Web Server" --> "User" : Wallet denied
autonumber resume
"Web Server" --> "User" --: Client wallet connected response
"User" --> "Web Server" : Client sent Data
"Web Server" --> "Crypto Wallet" ++: Generate Transaction
"Crypto Wallet" --> "User" --: Response transaction signature and wait for user confirmation
alt User denied transaction signature (false)
    autonumber stop
    "User" --> "Crypto Wallet" ++: Client denied transaction
    "Crypto Wallet" --> "Web Server" --++: Transaction denied
    "Web Server" --> "User" --: Data denied
else User confirmed transaction signature (true)
    autonumber resume
    "User" --> "Crypto Wallet" ++: Client confirmed transaction
    "Crypto Wallet" --> "Web Server" --++: Confirmed transaction
    "Web Server" --> "Blockchain" ++: Send data encrypted
    "Blockchain" --> "Web Server" --: Successful save data
    "Web Server" --> "User" --: Response data save successful
end
@enduml