@startuml
actor User
autonumber "<b>(0)"
"User" -> "Web Service" ++: Request Login Page \nGET /oauth
"Web Service" --> "User" --++: Reponse Login Page Content\nGET /oauth
"User" -> "Web Service" --++: Enter user credentials\n[email,password]\nPOST /oauth
"Web Service" -> "Authorization Server" ++: Request Authorization
note over "Authorization Server": Set client_id,redirect_uri,\nresponse_type=code\nfor web service itself
"Authorization Server" -> "Authorization Server" ++: Encrypt user credentials
"Authorization Server" -> "Blockchain" --++: Request user credentials for verification
"Blockchain" --> "Authorization Server" --: Response user data validity status
alt Invalid user credentials (false)
    autonumber stop
    "Authorization Server" --> "Web Service" ++: Authentication denied
    "Web Service" --> "User" --: Response notification\n"Username or Password Incorrect"
else valid user credentials (true)
    autonumber resume
    "Authorization Server" -> "Blockchain" ++: Call resource client credential
    "Blockchain" --> "Authorization Server" --: Response resource client credential
    "Authorization Server" -> "Authorization Server" ++: Grant and Generate Authorization Code & Encrypt
    "Authorization Server" -> "Blockchain" --++: Send authorization code credential
    "Blockchain" --> "Authorization Server" --: Response 
    "Authorization Server" --> "Web Service" --++: Response Authorization Code
    "Web Service" -> "Authorization Server" --++: Exchange authorization code for Access Token
    note over "Authorization Server": set client_id,client_secret,redirect_uri,\ngrant_type=authorization_code\nfor web service itself
    "Authorization Server" -> "Blockchain" ++: Call resource client credential
    "Blockchain" --> "Authorization Server" --: Response resource client credential
    "Authorization Server" -> "Authorization Server" ++: Generate Access Token & Encrypt
    "Authorization Server" -> "Blockchain" --++: Send access token credential
    "Blockchain" --> "Authorization Server" --: Response 
    "Authorization Server" --> "Web Service" --++: Response access token credential
    "Web Service" -> "Authorization Server" --++: Call resource user with Access Token
    "Authorization Server" -> "Blockchain" ++: Call resource user credential
    "Blockchain" --> "Authorization Server" --: Response user credential
    "Authorization Server" --> "Web Service" --: Set Cookie-based=[access_token,user_credential]
    "Web Service" --> "User" --: Redirect to Page\nGET /[redirect_uri]
end


@enduml


